# Generated by Django 5.2.1 on 2025-06-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bookrental'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon_id',
            field=models.CharField(blank=True, help_text='Amazon product identifier for affiliate links', max_length=20, null=True),
        ),
    ]
